export const uiStore = $state({
  tooltipMessage: null,
  tooltipTarget: null,
  showTooltips: true,
  settingsOpen: false,
  canvasSizeOpen: false,
  exportOpen: false,
  colorPickerOpen: false,
  vectorTransformOpen: false,
  dragging: false,
  dragX: null,
  dragY: null,
  dragTarget: null,
  dragSiblings: [],
  shortcuts: true,
  saveDialogOpen: false,
  saveSettings: {
    saveAsFileName: 'my drawing',
    preserveHistory: true,
    includePalette: true,
    includeReferenceLayers: true,
    includeRemovedActions: true,
  },
})
