//====================================//
//======== * * * State * * * =========//
//====================================//

export const canvas = $state({
  vectorGuiCVS: null,
  vectorGuiCTX: null,
  selectionGuiCVS: null,
  selectionGuiCTX: null,
  resizeOverlayCVS: null,
  resizeOverlayCTX: null,
  cursorCVS: null,
  cursorCTX: null,
  backgroundCVS: null,
  backgroundCTX: null,
  offScreenCVS: null,
  offScreenCTX: null,
  previewCVS: null,
  previewCTX: null,
  thumbnailCVS: null,
  thumbnailCTX: null,
  sharpness: null,
  zoom: null,
  zoomAtLastDraw: null,
  layers: [],
  activeLayerCount: 0,
  currentLayer: null,
  tempLayer: null,
  pastedLayer: null,
  hiddenLayer: null,
  bgColor: 'rgba(131, 131, 131, 0.5)',
  borderColor: 'black',
  pointerEvent: 'none',
  sizePointerState: 'none',
  xOffset: null,
  yOffset: null,
  previousXOffset: null,
  previousYOffset: null,
  subPixelX: null,
  subPixelY: null,
  previousSubPixelX: null,
  previousSubPixelY: null,
  zoomPixelX: null,
  zoomPixelY: null,
  gui: {
    lineWidth: null,
    renderRadius: null,
    collisionRadius: null,
  },
})
