/**
 * Globally keep track of which keys are being pressed or held
 */
export const keys = {
  ArrowLeft: false,
  ArrowRight: false,
  MetaLeft: false, //command key
  MetaRight: false,
  Space: false,
  AltLeft: false, //option key
  AltRight: false,
  ShiftLeft: false,
  ShiftRight: false,
  KeyA: false,
  KeyB: false,
  KeyC: false,
  KeyD: false,
  KeyE: false,
  KeyF: false,
  KeyG: false,
  KeyH: false,
  KeyI: false,
  KeyJ: false,
  KeyK: false,
  KeyL: false,
  KeyM: false,
  KeyN: false,
  KeyO: false,
  KeyP: false,
  KeyQ: false,
  KeyR: false,
  KeyS: false,
  KeyT: false,
  KeyU: false,
  KeyV: false,
  KeyW: false,
  KeyX: false,
  KeyY: false,
  KeyZ: false,
}
